export enum ChargerStatus {
  CHARGING = 'CHARGING',
  NONE = 'NONE',
  NONE_ELECTRIC = 'NONE_ELECTRIC',
}
export enum ChargeStatus {
  RAPIDITY = 'RAPIDITY',
  SLOW_CHARGE='SLOW_CHARGE',
  RAPIDITY_AND_SLOW='RAPIDITY_AND_SLOW',
  NONE = 'NONE',
}
